name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build-clang:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set CC and CXX to use Clang/LLVM 15
      run: |
        echo "CC=$(brew --prefix llvm@15)/bin/clang" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix llvm@15)/bin/clang++" >> $GITHUB_ENV
        echo "CPATH=/usr/local/include:$CPATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH" >> $GITHUB_ENV

    - name: Print compiler version
      run: ${{ env.CC }} --version

    - name: Install required packages
      run: |
        brew update
        brew install automake

    - name: Install zimg
      run: |
        git clone https://github.com/sekrit-twc/zimg --depth 1 --shallow-submodules --recurse-submodules
        pushd zimg
        ./autogen.sh
        ./configure
        make -j3
        sudo make install -j3
        popd
        rm -rf zimg

    - uses: actions/setup-python@v4
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: '3.11'

    - name: Install/upgrade required Python packages
      run: |
        python -m pip install -U pip
        pip install -U cython setuptools wheel

    - name: configure
      run: |
        ./autogen.sh
        ./configure

    - name: make
      run: make -j3

    - name: make install
      run: |
        sudo make install -j3
        pip install .

    - name: Run test
      run: python -m unittest discover -s test -p "*test.py"
